# Service para expor a API REST
apiVersion: v1
kind: Service
metadata:
  name: recommender-api-service
  labels:
    app: recommender-api
spec:
  type: ClusterIP
  ports:
  - port: 50024  # porta designada para matheussilva
    targetPort: 5000  # porta do container (Flask)
    protocol: TCP
    name: http
  selector:
    app: recommender-api  # seleciona pods do deployment