apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pv.yaml
  - api-deployment.yaml
  - api-service.yaml
  - model-generator-job.yaml
  - pvc.yaml
  - dataset-config.yaml
  - argocd-application.yaml

namespace: matheussilva

commonLabels:
  app.kubernetes.io/name: recommender
  app.kubernetes.io/instance: matheussilva
  app.kubernetes.io/managed-by: argocd