# PersistentVolumeClaim para acessar o volume compartilhado entre containers
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recommender-pvc  # Nome do PVC que será referenciado nos pods
spec:
  accessModes:
    - ReadWriteMany  # Permite leitura/escrita por múltiplos pods
  resources:
    requests:
      storage: 1Gi  # Requisita 1GB de espaço
  storageClassName: standard  # Usando storageClass padrão