apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-matheussilva
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-matheussilva
  template:
    metadata:
      labels:
        app: frontend-matheussilva
    spec:
      containers:
      - name: frontend
        image: soramf/frontend-tp2-matheus:0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 50024