apiVersion: batch/v1
kind: Job
metadata:
  name: recommend-rules-matheussilva
spec:
  template:
    spec:
      containers:
        - name: recommend-rules-matheussilva
          image: soramf/recommend-rules-tp2-matheus:0.2
          volumeMounts:
            - mountPath: /recommend-rules
              name: rules-shared
      restartPolicy: Never
      volumes:
        - name: rules-shared
          persistentVolumeClaim:
            claimName: recommend-rules
  backoffLimit: 1