apiVersion: batch/v1
kind: Job
metadata:
  name: ml-rules-matheussilva
spec:
  template:
    spec:
      containers:
        - name: ml-rules-matheussilva
          image: soramf/ml_rules-tp2-matheus:0.1
          volumeMounts:
            - mountPath: /ml_rules
              name: rules-shared
      restartPolicy: Never
      volumes:
        - name: rules-shared
          persistentVolumeClaim:
            claimName: ml-rules
  backoffLimit: 1