apiVersion: v1
kind: Service
metadata:
  name: service-playlist-matheussilva
  namespace: matheussilva
spec:
  selector:
    app: rest-api-server-matheussilva
  ports:
    - protocol: TCP
      port: 50024
      targetPort: 50024